[[items]]
name = "Open GitHub"
type = "url"
keywords = ["git", "code"]
[items.payload]
url = "https://github.com"
[[items]]
name = "linux"
type = "snippet"
keywords = ["linux", "command"]
[items.payload]
snippet = "https://linuxcommand.com"
[[items]]
name = "翻译"
type = "snippet"
keywords = ["English", "英语"]
[items.payload]
snippet = "你是一位专业的翻译家，请你将下述英文翻译成中文。"
